---
server:
    port: 8081
grails:
    profile: rest-api
    codegen:
        defaultPackage: ufracred.api
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    cors:
        enabled: true
        allowedOrigins: [ '*' ]
        allowCredentials: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    dbCreate: "update"
    driverClassName: "com.mysql.jdbc.Driver"
    dialect: "org.hibernate.dialect.MySQL8Dialect"
    url: "jdbc:mysql://localhost:3306/ufracred?useSSL=false"
    username: "root"
    password: "123456789"


environments:
    development:
        dataSource:
            dbCreate: "update"
            driverClassName: "com.mysql.jdbc.Driver"
            dialect: "org.hibernate.dialect.MySQL8Dialect"
            url: "jdbc:mysql://localhost:3306/ufracred?useSSL=false"
            username: "root"
            password: "123456789"
    test:
        dataSource:
            dbCreate: "update"
            driverClassName: "com.mysql.jdbc.Driver"
            dialect: "org.hibernate.dialect.MySQL8Dialect"
            url: "jdbc:mysql://localhost:3306/ufracred?useSSL=false"
            username: "root"
            password: "123456789"
    production:
        dataSource:
            dbCreate: "update"
            driverClassName: "com.mysql.jdbc.Driver"
            dialect: "org.hibernate.dialect.MySQL8Dialect"
            url: "jdbc:mysql://localhost:3306/ufracred?useSSL=false"
            username: "root"
            password: "123456789"
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
grails:
    plugin:
        springsecurity:
            rest:
                token:
                    storage:
                        jwt:
                            secret: "krZa6zXMRu/YcSgIDgnuaWEvWewwqx1RBq/hV7qY+Bg="